### ISSUE TITLE
Docker has changed versioning

### ISSUE THREAD

**Issue by vek0ng** [howtowhale/dvm#152] opened 2017-03-05 08:20 UTC
Since Feb 20th, Docker introduced new versioning. DVM cannot detect and install latest Docker version.

```
$ dvm ls-remote
```

Got:
```
...
1.12.6
1.13.0
1.13.1
```
Expected:
```
1.12.6
1.13.0
1.13.1
17.03.0-ce  <-- Docker's new versioning 
```
DVM version:
```
$ dvm --version
Docker Version Manager version 0.7.0 (5a8942b)
```

**Comment by carolynvs** [comment] 2017-03-05 14:49
@vek0ng Thanks for the heads up! I'll get cracking on an update.

**Comment by carolynvs** [comment] 2017-03-08 19:12
@vek0ng A new version has been released with this fix: https://github.com/howtowhale/dvm/releases/tag/0.8.0. You should now see new `-ce` releases when listing remote versions.

Please checkout the release notes, as the install/upgrade procedure was slightly impacted when this repository moved.

**Comment by vek0ng** [comment] 2017-03-09 04:21
Thanks, Carolyn for the quick fix. I'll check it and advise you if there
are remaining issues.

Best,
Victor

On Mar 9, 2017 3:12 AM, "Carolyn Van Slyck" <notifications@github.com>
wrote:

@vek0ng <https://github.com/vek0ng> A new version has been released with
this fix: https://github.com/howtowhale/dvm/releases/tag/0.8.0. You should
now see new -ce releases when listing remote versions.

Please checkout the release notes, as the install/upgrade procedure was
slightly impacted when this repository moved.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/howtowhale/dvm/issues/152#issuecomment-285138056>, or mute
the thread

**Comment by matthewberry** [comment] 2017-03-11 15:27
Thanks for the quick fix! I'm now running 0.8.0 and able to see the new CE release with ls-remote. Installing the new CE release fails, though:

`$ dvm-helper use 17.3.0-ce
17.3.0-ce is not installed. Installing now...
Installing 17.3.0-ce...
Unable to download https://get.docker.com/builds/Linux/x86_64/docker-17.3.0-ce. (Status 403)
`
I also tried `dvm-helper use 17.03.0-ce`--note the "03" instead of "3"--with the same result. Am I doing something wrong?

**Comment by carolynvs** [comment] 2017-03-11 23:25
Doh! Thanks for pointing out the problem is the leading `0`. I'll get that fixed.

**Closed** 2017-03-12 03:30 UTC
Labels: in progress

**Comment by carolynvs** [comment] 2017-03-13 00:33
Okay second try! https://github.com/howtowhale/dvm/releases/tag/0.8.2 Let me know if you run into problems.

**Comment by matthewberry** [comment] 2017-03-13 02:15
Works like a charm. Thanks a bunch!
